# https://docs.astral.sh/ruff/configuration/
[tool.ruff]
line-length = 120
select = [
    "I",  # isort
    "F",  # pyflakes
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "UP", # pyupgrade
]
ignore = ["F401"]

[tool.pyright]
exclude = ["**/__pycache__", "data", "logs"]
typeCheckingMode = "off"
